# Model arguments
model_name_or_path: kykim0/llama3-8b-ultrachat-sft-itt
use_flash_attention_2: false
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  allenai/ultrafeedback_binarized_cleaned: 1.0
dataset_splits:
  - train_prefs
  - test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bt_beta: null
bf16: true
beta: 0.01
learning_rate: 5.0e-7
gradient_accumulation_steps: 16
gradient_checkpointing: true
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
max_steps: -1
optim: adamw_torch
resume_from_checkpoint: False
loss_type: sigmoid

output_dir: ../checkpoints/mmpo-dpo-llama3-8b
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
report_to:
  - wandb
run_name: mmpo-dpo-llama3-8b
save_strategy: "steps"
save_steps: 950
save_total_limit: null
seed: 42
warmup_ratio: 0.3
hub_model_id: mmpo-dpo-llama3-8b
push_to_hub: false